# Generated by Django 4.2 on 2023-04-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_file',
            field=models.ImageField(upload_to='images'),
        ),
    ]
